name: GitHub Action flow to Docker hub 

on:
  push:
    branches: [main]

jobs:
  build-push-images:
    name: Budowa i publikacja obrazw na repozytorium
    runs-on: ubuntu-latest

    steps:
      # Akcja: "checkout" - sprawdza, czy workflow ma poprawny dostęp do repo
      - name: Checkout code
        uses: actions/checkout@v2
      # Akcja: "docker/setup-buildx-action" - konfiguruje buildx'a, przez co będzie możliwość budowania obrazów na wiele architektur
      - name: Buildx set-up
        id: buildx
        uses: docker/setup-buildx-action@v1
      # Akcja: "docker/setup-qemu-action" - "instalacja" emelatora dla wielu architektur
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      # Akcja: "cache" - umożliwia manipulowanie cache pomiędzy uruchomieniami kolejnymi sesjami GitHub Actions
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      # Akcja: "docker/login-action" - logowanie na konto Dockerhub
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      # Akcja: "build-push-action" - zbudowanie i wypchnięcie obrazów na DockerHub registry
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: ./dockerfile.v1
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/lab:ghfront1
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      # Skrypt: "Move cache" – cykliczne aktualizowanie cache'a 
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
          